<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!--
      فقط MediatR برای IDomainEvent : INotification لازم است
      هیچ وابستگی دیگری در لایه Domain نباید وجود داشته باشد
    -->
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

</Project>
